spring:
  datasource:
    url: jdbc:mysql://221.235.53.167:3306/gttest?characterEncoding=utf8
    username: gttest
    password: gttest0319
    driver-class-name: com.mysql.jdbc.Driver
    
mybatis:
  mapper-locations: classpath:mapper/*.xml
    