spring:
  datasource:
    url: jdbc:mysql://你的IP:你的端口/你的数据库?characterEncoding=utf8
    username: 用户名
    password: 密码
    driver-class-name: com.mysql.jdbc.Driver
    
mybatis:
  mapper-locations: classpath:mapper/*.xml
    
